export const LOCATION = [
    { name: "none", value: "none",id:"location" },
    { name: "Afghanistan", value: "af" },
    { name: "Åland Islands", value: "ax", },
    { name: "Albania", value: "al", },
    { name: "Algeria", value: "dz", },
    { name: "American Samoa", value: "as", },
    { name: "AndorrA", value: "ad", },
    { name: "Angola", value: "ao", },
    { name: "Anguilla", value: "ai", },
    { name: "Antarctica", value: "aq", },
    { name: "Antigua and Barbuda", value: "ag", },
    { name: "Argentina", value: "ar", },
    { name: "Armenia", value: "am", },
    { name: "Aruba", value: "aw", },
    { name: "Australia", value: "au", },
    { name: "Austria", value: "at", },
    { name: "Azerbaijan", value: "az", },
    { name: "Bahamas", value: "bs", },
    { name: "Bahrain", value: "bh", },
    { name: "Bangladesh", value: "bd", },
    { name: "Barbados", value: "bb", },
    { name: "Belarus", value: "by", },
    { name: "Belgium", value: "be", },
    { name: "Belize", value: "bz", },
    { name: "Benin", value: "bj", },
    { name: "Bermuda", value: "bm", },
    { name: "Bhutan", value: "bt", },
    { name: "Bolivia", value: "bo", },
    { name: "Bosnia and Herzegovina", value: "ba", },
    { name: "Botswana", value: "bw", },
    { name: "Bouvet Island", value: "bv", },
    { name: "Brazil", value: "br", },
    { name: "British Indian Ocean Territory", value: "io", },
    { name: "Brunei Darussalam", value: "bn", },
    { name: "Bulgaria", value: "bg", },
    { name: "Burkina Faso", value: "bf", },
    { name: "Burundi", value: "bi", },
    { name: "Cambodia", value: "kh", },
    { name: "Cameroon", value: "cm", },
    { name: "Canada", value: "ca", },
    { name: "Cape Verde", value: "cv", },
    { name: "Cayman Islands", value: "ky", },
    { name: "Central African Republic", value: "cf", },
    { name: "Chad", value: "td", },
    { name: "Chile", value: "cl", },
    { name: "China", value: "cn", },
    { name: "Christmas Island", value: "cx", },
    { name: "Cocos (Keeling) Islands", value: "cc", },
    { name: "Colombia", value: "co", },
    { name: "Comoros", value: "km", },
    { name: "Congo", value: "cg", },
    { name: "Congo, The Democratic Republic of the", value: "cd", },
    { name: "Cook Islands", value: "ck", },
    { name: "Costa Rica", value: "cr", },
    { name: 'Cote D"Ivoire', value: "ci", },
    { name: "Croatia", value: "hr", },
    { name: "Cuba", value: "cu", },
    { name: "Cyprus", value: "cy", },
    { name: "Czech Republic", value: "cz", },
    { name: "Denmark", value: "dk", },
    { name: "Djibouti", value: "dj", },
    { name: "Dominica", value: "dm", },
    { name: "Dominican Republic", value: "do", },
    { name: "Ecuador", value: "ec", },
    { name: "Egypt", value: "eg", },
    { name: "El Salvador", value: "sv", },
    { name: "Equatorial Guinea", value: "gq", },
    { name: "Eritrea", value: "er", },
    { name: "Estonia", value: "ee", },
    { name: "Ethiopia", value: "et", },
    { name: "Falkland Islands (Malvinas)", value: "fk", },
    { name: "Faroe Islands", value: "fo", },
    { name: "Fiji", value: "fj", },
    { name: "Finland", value: "fi", },
    { name: "France", value: "fr", },
    { name: "French Guiana", value: "gf", },
    { name: "French Polynesia", value: "pf", },
    { name: "French Southern Territories", value: "tf", },
    { name: "Gabon", value: "ga", },
    { name: "Gambia", value: "gm", },
    { name: "Georgia", value: "ge", },
    { name: "Germany", value: "de", },
    { name: "Ghana", value: "gh", },
    { name: "Gibraltar", value: "gi", },
    { name: "Greece", value: "gr", },
    { name: "Greenland", value: "gl", },
    { name: "Grenada", value: "gd", },
    { name: "Guadeloupe", value: "gp", },
    { name: "Guam", value: "gu", },
    { name: "Guatemala", value: "gt", },
    { name: "Guernsey", value: "gg", },
    { name: "Guinea", value: "gn", },
    { name: "Guinea-Bissau", value: "gw", },
    { name: "Guyana", value: "gy", },
    { name: "Haiti", value: "ht", },
    { name: "Heard Island and Mcdonald Islands", value: "hm", },
    { name: "Holy See (Vatican City State)", value: "va", },
    { name: "Honduras", value: "hn", },
    { name: "Hong Kong", value: "hk", },
    { name: "Hungary", value: "hu", },
    { name: "Iceland", value: "is", },
    { name: "India", value: "in", },
    { name: "Indonesia", value: "id", },
    { name: "Iran, Islamic Republic Of", value: "ir", },
    { name: "Iraq", value: "iq", },
    { name: "Ireland", value: "ie", },
    { name: "Isle of Man", value: "im", },
    { name: "Israel", value: "il", },
    { name: "Italy", value: "it", },
    { name: "Jamaica", value: "jm", },
    { name: "Japan", value: "jp", },
    { name: "Jersey", value: "je", },
    { name: "Jordan", value: "jo", },
    { name: "Kazakhstan", value: "kz", },
    { name: "Kenya", value: "ke", },
    { name: "Kiribati", value: "ki", },
    { name: 'Korea, Democratic People"S Republic of', value: "kp", },
    { name: "Korea, Republic of", value: "kr", },
    { name: "Kuwait", value: "kw", },
    { name: "Kyrgyzstan", value: "KG", },
    { name: 'Lao People"S Democratic Republic', value: "la", },
    { name: "Latvia", value: "lv", },
    { name: "Lebanon", value: "lb", },
    { name: "Lesotho", value: "ls", },
    { name: "Liberia", value: "lr", },
    { name: "Libyan Arab Jamahiriya", value: "ly", },
    { name: "Liechtenstein", value: "li", },
    { name: "Lithuania", value: "lt", },
    { name: "Luxembourg", value: "lu", },
    { name: "Macao", value: "MO", },
    { name: "Macedonia, The Former Yugoslav Republic of", value: "mk", },
    { name: "Madagascar", value: "mg", },
    { name: "Malawi", value: "mw", },
    { name: "Malaysia", value: "my", },
    { name: "Maldives", value: "mv", },
    { name: "Mali", value: "ml", },
    { name: "Malta", value: "mt", },
    { name: "Marshall Islands", value: "mh", },
    { name: "Martinique", value: "mq", },
    { name: "Mauritania", value: "mr", },
    { name: "Mauritius", value: "mu", },
    { name: "Mayotte", value: "yt", },
    { name: "Mexico", value: "mx", },
    { name: "Micronesia, Federated States of", value: "fm", },
    { name: "Moldova, Republic of", value: "md", },
    { name: "Monaco", value: "mc", },
    { name: "Mongolia", value: "mn", },
    { name: "Montserrat", value: "ms", },
    { name: "Morocco", value: "ma", },
    { name: "Mozambique", value: "mz", },
    { name: "Myanmar", value: "mm", },
    { name: "Namibia", value: "na", },
    { name: "Nauru", value: "nr", },
    { name: "Nepal", value: "np", },
    { name: "Netherlands", value: "nl", },
    { name: "Netherlands Antilles", value: "an", },
    { name: "New Caledonia", value: "nc", },
    { name: "New Zealand", value: "nz", },
    { name: "Nicaragua", value: "ni", },
    { name: "Niger", value: "ne", },
    { name: "Nigeria", value: "ng", },
    { name: "Niue", value: "nu", },
    { name: "Norfolk Island", value: "nf", },
    { name: "Northern Mariana Islands", value: "mp", },
    { name: "Norway", value: "no", },
    { name: "Oman", value: "om", },
    { name: "Pakistan", value: "pk", },
    { name: "Palau", value: "PW", },
    { name: "Palestinian Territory, Occupied", value: "ps", },
    { name: "Panama", value: "pa", },
    { name: "Papua New Guinea", value: "pg", },
    { name: "Paraguay", value: "py", },
    { name: "Peru", value: "pe", },
    { name: "Philippines", value: "ph", },
    { name: "Pitcairn", value: "pn", },
    { name: "Poland", value: "pl", },
    { name: "Portugal", value: "pt", },
    { name: "Puerto Rico", value: "pr", },
    { name: "Qatar", value: "qa", },
    { name: "Reunion", value: "re", },
    { name: "Romania", value: "ro", },
    { name: "Russian Federation", value: "ru", },
    { name: "RWANDA", value: "rw", },
    { name: "Saint Helena", value: "sh", },
    { name: "Saint Kitts and Nevis", value: "kn", },
    { name: "Saint Lucia", value: "lc", },
    { name: "Saint Pierre and Miquelon", value: "pm", },
    { name: "Saint Vincent and the Grenadines", value: "vc", },
    { name: "Samoa", value: "ws", },
    { name: "San Marino", value: "sm", },
    { name: "Sao Tome and Principe", value: "st", },
    { name: "Saudi Arabia", value: "sa", },
    { name: "Senegal", value: "sn", },
    { name: "Serbia and Montenegro", value: "cs", },
    { name: "Seychelles", value: "sc", },
    { name: "Sierra Leone", value: "sl", },
    { name: "Singapore", value: "sg", },
    { name: "Slovakia", value: "sk", },
    { name: "Slovenia", value: "si", },
    { name: "Solomon Islands", value: "sb", },
    { name: "Somalia", value: "so", },
    { name: "South Africa", value: "za", },
    { name: "South Georgia and the South Sandwich Islands", value: "gs", },
    { name: "Spain", value: "es", },
    { name: "Sri Lanka", value: "lk", },
    { name: "Sudan", value: "sd", },
    { name: "Suriname", value: "sr", },
    { name: "Svalbard and Jan Mayen", value: "sj", },
    { name: "Swaziland", value: "sz", },
    { name: "Sweden", value: "se", },
    { name: "Switzerland", value: "ch", },
    { name: "Syrian Arab Republic", value: "sy", },
    { name: "Taiwan, Province of China", value: "tw", },
    { name: "Tajikistan", value: "tj", },
    { name: "Tanzania, United Republic of", value: "tz", },
    { name: "Thailand", value: "th", },
    { name: "Timor-Leste", value: "tl", },
    { name: "Togo", value: "tg", },
    { name: "Tokelau", value: "tk", },
    { name: "Tonga", value: "to", },
    { name: "Trinidad and Tobago", value: "tt", },
    { name: "Tunisia", value: "tn", },
    { name: "Turkey", value: "tr", },
    { name: "Turkmenistan", value: "tm", },
    { name: "Turks and Caicos Islands", value: "tc", },
    { name: "Tuvalu", value: "tv", },
    { name: "Uganda", value: "ug", },
    { name: "Ukraine", value: "ua", },
    { name: "United Arab Emirates", value: "ae", },
    { name: "United Kingdom", value: "gb", },
    { name: "United States", value: "us", },
    { name: "United States Minor Outlying Islands", value: "um", },
    { name: "Uruguay", value: "uy", },
    { name: "Uzbekistan", value: "uz", },
    { name: "Vanuatu", value: "vu", },
    { name: "Venezuela", value: "ve", },
    { name: "Viet Nam", value: "vn", },
    { name: "Virgin Islands, British", value: "vg", },
    { name: "Virgin Islands, U.S.", value: "vi", },
    { name: "Wallis and Futuna", value: "wf", },
    { name: "Western Sahara", value: "eh", },
    { name: "Yemen", value: "ye", },
    { name: "Zambia", value: "zm", },
    { name: "Zimbabwe", value: "zw", },
  ];